## trying to replicat conflicts on main branch
apiVersion: v1
kind: Pod
metadata:
  name: mynginx-testing
  labels:            
    devops: '18'
    company: talent
    type: create
spec: 
  containers:         
  - name: nginx18
    image: nginx:1.20.1
    ports:
    - containerPort: 80
  nodeName: k8-18-worker-1
